import { InstructorUser } from "../../types/user";

export const mockInstructors: InstructorUser[] = [
  {
    id: "inst-1",
    name: "Dr. Sarah Johnson",
    email: "sarah.johnson@e-broker.com",
    role: "instructor",
    specialization: "Web Development",
    bio: "10+ years experience in full-stack development and teaching. Specialized in React, Node.js, and modern web technologies.",
    courses_created: 12,
    total_students: 450,
    rating: 4.8,
    status: "active",
    createdAt: "2024-01-15",
    avatar: "/avatars/sarah.jpg",
  },
  {
    id: "inst-2",
    name: "Michael Chen",
    email: "michael.chen@e-broker.com",
    role: "instructor",
    specialization: "Data Science",
    bio: "PhD in Computer Science. Expert in machine learning, Python, and data visualization.",
    courses_created: 8,
    total_students: 320,
    rating: 4.9,
    status: "active",
    createdAt: "2024-02-10",
    avatar: "/avatars/michael.jpg",
  },
  {
    id: "inst-3",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@e-broker.com",
    role: "instructor",
    specialization: "Mobile Development",
    bio: "Senior mobile developer with expertise in Flutter, React Native, and iOS/Android native development.",
    courses_created: 15,
    total_students: 580,
    rating: 4.7,
    status: "active",
    createdAt: "2023-11-20",
    avatar: "/avatars/emily.jpg",
  },
  {
    id: "inst-4",
    name: "David Kim",
    email: "david.kim@e-broker.com",
    role: "instructor",
    specialization: "DevOps & Cloud",
    bio: "AWS certified solutions architect. Specialized in Docker, Kubernetes, and CI/CD pipelines.",
    courses_created: 6,
    total_students: 210,
    rating: 4.6,
    status: "active",
    createdAt: "2024-03-05",
    avatar: "/avatars/david.jpg",
  },
  {
    id: "inst-5",
    name: "Lisa Anderson",
    email: "lisa.anderson@e-broker.com",
    role: "instructor",
    specialization: "UI/UX Design",
    bio: "Award-winning designer with 8 years of experience. Expert in Figma, Adobe XD, and design systems.",
    courses_created: 10,
    total_students: 390,
    rating: 4.9,
    status: "active",
    createdAt: "2024-01-25",
    avatar: "/avatars/lisa.jpg",
  },
  {
    id: "inst-6",
    name: "James Wilson",
    email: "james.wilson@e-broker.com",
    role: "instructor",
    specialization: "Cybersecurity",
    bio: "Certified ethical hacker and security consultant. Teaching network security and penetration testing.",
    courses_created: 7,
    total_students: 280,
    rating: 4.8,
    status: "active",
    createdAt: "2024-02-15",
    avatar: "/avatars/james.jpg",
  },
  {
    id: "inst-7",
    name: "Maria Garcia",
    email: "maria.garcia@e-broker.com",
    role: "instructor",
    specialization: "Backend Development",
    bio: "Expert in Node.js, Python, and microservices architecture. Former tech lead at major tech companies.",
    courses_created: 9,
    total_students: 340,
    rating: 4.7,
    status: "inactive",
    createdAt: "2023-12-10",
    avatar: "/avatars/maria.jpg",
  },
  {
    id: "inst-8",
    name: "Robert Taylor",
    email: "robert.taylor@e-broker.com",
    role: "instructor",
    specialization: "Game Development",
    bio: "15 years in game industry. Specialized in Unity, Unreal Engine, and game design principles.",
    courses_created: 11,
    total_students: 420,
    rating: 4.8,
    status: "active",
    createdAt: "2024-01-05",
    avatar: "/avatars/robert.jpg",
  },
  {
    id: "inst-9",
    name: "Jennifer Lee",
    email: "jennifer.lee@e-broker.com",
    role: "instructor",
    specialization: "Database Management",
    bio: "Database architect with expertise in SQL, NoSQL, MongoDB, and PostgreSQL optimization.",
    courses_created: 5,
    total_students: 190,
    rating: 4.6,
    status: "active",
    createdAt: "2024-03-20",
    avatar: "/avatars/jennifer.jpg",
  },
  {
    id: "inst-10",
    name: "Thomas Brown",
    email: "thomas.brown@e-broker.com",
    role: "instructor",
    specialization: "AI & Machine Learning",
    bio: "Research scientist specializing in deep learning, neural networks, and AI applications.",
    courses_created: 13,
    total_students: 510,
    rating: 4.9,
    status: "active",
    createdAt: "2023-10-15",
    avatar: "/avatars/thomas.jpg",
  },
  {
    id: "inst-11",
    name: "Patricia Martinez",
    email: "patricia.martinez@e-broker.com",
    role: "instructor",
    specialization: "Frontend Development",
    bio: "Vue.js and Angular expert. 7 years building scalable frontend applications.",
    courses_created: 8,
    total_students: 295,
    rating: 4.7,
    status: "active",
    createdAt: "2024-02-01",
    avatar: "/avatars/patricia.jpg",
  },
  {
    id: "inst-12",
    name: "Christopher Davis",
    email: "christopher.davis@e-broker.com",
    role: "instructor",
    specialization: "Blockchain Development",
    bio: "Blockchain architect specializing in Ethereum, Solidity, and smart contract development.",
    courses_created: 6,
    total_students: 180,
    rating: 4.8,
    status: "active",
    createdAt: "2024-03-10",
    avatar: "/avatars/christopher.jpg",
  },
  {
    id: "inst-13",
    name: "Nancy White",
    email: "nancy.white@e-broker.com",
    role: "instructor",
    specialization: "Digital Marketing",
    bio: "Marketing strategist with focus on SEO, content marketing, and social media.",
    courses_created: 9,
    total_students: 410,
    rating: 4.6,
    status: "active",
    createdAt: "2023-12-20",
    avatar: "/avatars/nancy.jpg",
  },
  {
    id: "inst-14",
    name: "Daniel Harris",
    email: "daniel.harris@e-broker.com",
    role: "instructor",
    specialization: "Software Testing",
    bio: "QA expert specializing in automated testing, TDD, and quality assurance best practices.",
    courses_created: 7,
    total_students: 245,
    rating: 4.7,
    status: "active",
    createdAt: "2024-01-30",
    avatar: "/avatars/daniel.jpg",
  },
  {
    id: "inst-15",
    name: "Karen Thompson",
    email: "karen.thompson@e-broker.com",
    role: "instructor",
    specialization: "Product Management",
    bio: "Senior product manager with experience launching 20+ successful products.",
    courses_created: 5,
    total_students: 320,
    rating: 4.9,
    status: "active",
    createdAt: "2024-02-25",
    avatar: "/avatars/karen.jpg",
  },
  {
    id: "inst-16",
    name: "Steven Clark",
    email: "steven.clark@e-broker.com",
    role: "instructor",
    specialization: "IoT Development",
    bio: "IoT specialist working with Arduino, Raspberry Pi, and embedded systems.",
    courses_created: 4,
    total_students: 150,
    rating: 4.5,
    status: "active",
    createdAt: "2024-03-15",
    avatar: "/avatars/steven.jpg",
  },
  {
    id: "inst-17",
    name: "Betty Lewis",
    email: "betty.lewis@e-broker.com",
    role: "instructor",
    specialization: "Business Analytics",
    bio: "Data analyst specializing in business intelligence, Tableau, and Power BI.",
    courses_created: 8,
    total_students: 380,
    rating: 4.8,
    status: "active",
    createdAt: "2023-11-10",
    avatar: "/avatars/betty.jpg",
  },
  {
    id: "inst-18",
    name: "Paul Walker",
    email: "paul.walker@e-broker.com",
    role: "instructor",
    specialization: "System Architecture",
    bio: "Solutions architect with 12 years designing scalable distributed systems.",
    courses_created: 6,
    total_students: 220,
    rating: 4.7,
    status: "inactive",
    createdAt: "2024-01-08",
    avatar: "/avatars/paul.jpg",
  },
  {
    id: "inst-19",
    name: "Sandra Hall",
    email: "sandra.hall@e-broker.com",
    role: "instructor",
    specialization: "Content Writing",
    bio: "Professional writer and content strategist. Teaching technical writing and documentation.",
    courses_created: 7,
    total_students: 290,
    rating: 4.6,
    status: "active",
    createdAt: "2024-02-18",
    avatar: "/avatars/sandra.jpg",
  },
  {
    id: "inst-20",
    name: "Kevin Allen",
    email: "kevin.allen@e-broker.com",
    role: "instructor",
    specialization: "Network Engineering",
    bio: "CCNA/CCNP certified. Expert in network design, routing, and switching.",
    courses_created: 5,
    total_students: 175,
    rating: 4.7,
    status: "active",
    createdAt: "2024-03-01",
    avatar: "/avatars/kevin.jpg",
  },
  {
    id: "inst-21",
    name: "Michelle Young",
    email: "michelle.young@e-broker.com",
    role: "instructor",
    specialization: "Graphic Design",
    bio: "Creative director with expertise in Adobe Creative Suite and brand identity design.",
    courses_created: 10,
    total_students: 425,
    rating: 4.8,
    status: "active",
    createdAt: "2023-12-05",
    avatar: "/avatars/michelle.jpg",
  },
  {
    id: "inst-22",
    name: "Brian King",
    email: "brian.king@e-broker.com",
    role: "instructor",
    specialization: "Agile & Scrum",
    bio: "Certified Scrum Master teaching agile methodologies and project management.",
    courses_created: 6,
    total_students: 310,
    rating: 4.9,
    status: "active",
    createdAt: "2024-01-20",
    avatar: "/avatars/brian.jpg",
  },
  {
    id: "inst-23",
    name: "Dorothy Wright",
    email: "dorothy.wright@e-broker.com",
    role: "instructor",
    specialization: "E-commerce",
    bio: "E-commerce consultant specializing in Shopify, WooCommerce, and online store optimization.",
    courses_created: 7,
    total_students: 265,
    rating: 4.6,
    status: "active",
    createdAt: "2024-02-12",
    avatar: "/avatars/dorothy.jpg",
  },
  {
    id: "inst-24",
    name: "George Lopez",
    email: "george.lopez@e-broker.com",
    role: "instructor",
    specialization: "Video Production",
    bio: "Filmmaker and video editor teaching video production and post-production techniques.",
    courses_created: 8,
    total_students: 340,
    rating: 4.7,
    status: "active",
    createdAt: "2023-11-25",
    avatar: "/avatars/george.jpg",
  },
  {
    id: "inst-25",
    name: "Helen Hill",
    email: "helen.hill@e-broker.com",
    role: "instructor",
    specialization: "Photography",
    bio: "Professional photographer teaching digital photography and photo editing.",
    courses_created: 9,
    total_students: 395,
    rating: 4.8,
    status: "active",
    createdAt: "2024-01-12",
    avatar: "/avatars/helen.jpg",
  },
];
