import { StudentUser } from "../../types/user";

export const mockStudents: StudentUser[] = [
  {
    id: "stud-1",
    name: "John Doe",
    email: "john.doe@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-01",
    grade_level: "Intermediate",
    courses_enrolled: 5,
    progress_percentage: 68,
    total_score: 850,
    status: "active",
    createdAt: "2024-03-01",
    avatar: "/avatars/john.jpg",
  },
  {
    id: "stud-2",
    name: "Alice Smith",
    email: "alice.smith@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-15",
    grade_level: "Advanced",
    courses_enrolled: 8,
    progress_percentage: 92,
    total_score: 1450,
    status: "active",
    createdAt: "2024-01-15",
    avatar: "/avatars/alice.jpg",
  },
  {
    id: "stud-3",
    name: "Bob Johnson",
    email: "bob.johnson@e-broker.com",
    role: "student",
    enrollment_date: "2024-04-10",
    grade_level: "Beginner",
    courses_enrolled: 2,
    progress_percentage: 35,
    total_score: 280,
    status: "active",
    createdAt: "2024-04-10",
    avatar: "/avatars/bob.jpg",
  },
  {
    id: "stud-4",
    name: "Emma Wilson",
    email: "emma.wilson@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-20",
    grade_level: "Intermediate",
    courses_enrolled: 6,
    progress_percentage: 75,
    total_score: 1120,
    status: "active",
    createdAt: "2024-02-20",
    avatar: "/avatars/emma.jpg",
  },
  {
    id: "stud-5",
    name: "Michael Brown",
    email: "michael.brown@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-15",
    grade_level: "Beginner",
    courses_enrolled: 3,
    progress_percentage: 45,
    total_score: 420,
    status: "active",
    createdAt: "2024-03-15",
    avatar: "/avatars/michael-b.jpg",
  },
  {
    id: "stud-6",
    name: "Sophia Martinez",
    email: "sophia.martinez@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-05",
    grade_level: "Advanced",
    courses_enrolled: 10,
    progress_percentage: 88,
    total_score: 1680,
    status: "active",
    createdAt: "2024-01-05",
    avatar: "/avatars/sophia.jpg",
  },
  {
    id: "stud-7",
    name: "William Davis",
    email: "william.davis@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-10",
    grade_level: "Intermediate",
    courses_enrolled: 4,
    progress_percentage: 60,
    total_score: 720,
    status: "active",
    createdAt: "2024-02-10",
    avatar: "/avatars/william.jpg",
  },
  {
    id: "stud-8",
    name: "Olivia Garcia",
    email: "olivia.garcia@e-broker.com",
    role: "student",
    enrollment_date: "2023-12-20",
    grade_level: "Advanced",
    courses_enrolled: 7,
    progress_percentage: 95,
    total_score: 1580,
    status: "active",
    createdAt: "2023-12-20",
    avatar: "/avatars/olivia.jpg",
  },
  {
    id: "stud-9",
    name: "James Anderson",
    email: "james.anderson@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-25",
    grade_level: "Beginner",
    courses_enrolled: 2,
    progress_percentage: 28,
    total_score: 210,
    status: "inactive",
    createdAt: "2024-03-25",
    avatar: "/avatars/james-a.jpg",
  },
  {
    id: "stud-10",
    name: "Isabella Taylor",
    email: "isabella.taylor@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-05",
    grade_level: "Intermediate",
    courses_enrolled: 5,
    progress_percentage: 70,
    total_score: 980,
    status: "active",
    createdAt: "2024-02-05",
    avatar: "/avatars/isabella.jpg",
  },
  {
    id: "stud-11",
    name: "Ethan Thomas",
    email: "ethan.thomas@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-20",
    grade_level: "Advanced",
    courses_enrolled: 9,
    progress_percentage: 85,
    total_score: 1520,
    status: "active",
    createdAt: "2024-01-20",
    avatar: "/avatars/ethan.jpg",
  },
  {
    id: "stud-12",
    name: "Mia Jackson",
    email: "mia.jackson@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-10",
    grade_level: "Beginner",
    courses_enrolled: 3,
    progress_percentage: 40,
    total_score: 360,
    status: "active",
    createdAt: "2024-03-10",
    avatar: "/avatars/mia.jpg",
  },
  {
    id: "stud-13",
    name: "Alexander White",
    email: "alexander.white@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-15",
    grade_level: "Intermediate",
    courses_enrolled: 6,
    progress_percentage: 78,
    total_score: 1180,
    status: "active",
    createdAt: "2024-02-15",
    avatar: "/avatars/alexander.jpg",
  },
  {
    id: "stud-14",
    name: "Charlotte Harris",
    email: "charlotte.harris@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-10",
    grade_level: "Advanced",
    courses_enrolled: 8,
    progress_percentage: 90,
    total_score: 1620,
    status: "active",
    createdAt: "2024-01-10",
    avatar: "/avatars/charlotte.jpg",
  },
  {
    id: "stud-15",
    name: "Daniel Martin",
    email: "daniel.martin@e-broker.com",
    role: "student",
    enrollment_date: "2024-04-01",
    grade_level: "Beginner",
    courses_enrolled: 1,
    progress_percentage: 15,
    total_score: 120,
    status: "active",
    createdAt: "2024-04-01",
    avatar: "/avatars/daniel.jpg",
  },
  {
    id: "stud-16",
    name: "Amelia Thompson",
    email: "amelia.thompson@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-25",
    grade_level: "Intermediate",
    courses_enrolled: 4,
    progress_percentage: 65,
    total_score: 820,
    status: "active",
    createdAt: "2024-02-25",
    avatar: "/avatars/amelia.jpg",
  },
  {
    id: "stud-17",
    name: "Benjamin Lee",
    email: "benjamin.lee@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-25",
    grade_level: "Advanced",
    courses_enrolled: 7,
    progress_percentage: 82,
    total_score: 1420,
    status: "active",
    createdAt: "2024-01-25",
    avatar: "/avatars/benjamin.jpg",
  },
  {
    id: "stud-18",
    name: "Harper Walker",
    email: "harper.walker@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-20",
    grade_level: "Beginner",
    courses_enrolled: 2,
    progress_percentage: 32,
    total_score: 250,
    status: "active",
    createdAt: "2024-03-20",
    avatar: "/avatars/harper.jpg",
  },
  {
    id: "stud-19",
    name: "Lucas Hall",
    email: "lucas.hall@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-01",
    grade_level: "Intermediate",
    courses_enrolled: 5,
    progress_percentage: 72,
    total_score: 1050,
    status: "active",
    createdAt: "2024-02-01",
    avatar: "/avatars/lucas.jpg",
  },
  {
    id: "stud-20",
    name: "Evelyn Allen",
    email: "evelyn.allen@e-broker.com",
    role: "student",
    enrollment_date: "2023-12-15",
    grade_level: "Advanced",
    courses_enrolled: 9,
    progress_percentage: 94,
    total_score: 1720,
    status: "active",
    createdAt: "2023-12-15",
    avatar: "/avatars/evelyn.jpg",
  },
  {
    id: "stud-21",
    name: "Mason Young",
    email: "mason.young@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-05",
    grade_level: "Beginner",
    courses_enrolled: 3,
    progress_percentage: 38,
    total_score: 310,
    status: "active",
    createdAt: "2024-03-05",
    avatar: "/avatars/mason.jpg",
  },
  {
    id: "stud-22",
    name: "Ella King",
    email: "ella.king@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-30",
    grade_level: "Intermediate",
    courses_enrolled: 6,
    progress_percentage: 80,
    total_score: 1240,
    status: "active",
    createdAt: "2024-01-30",
    avatar: "/avatars/ella.jpg",
  },
  {
    id: "stud-23",
    name: "Logan Wright",
    email: "logan.wright@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-18",
    grade_level: "Advanced",
    courses_enrolled: 8,
    progress_percentage: 87,
    total_score: 1560,
    status: "active",
    createdAt: "2024-02-18",
    avatar: "/avatars/logan.jpg",
  },
  {
    id: "stud-24",
    name: "Avery Lopez",
    email: "avery.lopez@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-28",
    grade_level: "Beginner",
    courses_enrolled: 2,
    progress_percentage: 25,
    total_score: 190,
    status: "active",
    createdAt: "2024-03-28",
    avatar: "/avatars/avery.jpg",
  },
  {
    id: "stud-25",
    name: "Sebastian Hill",
    email: "sebastian.hill@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-08",
    grade_level: "Intermediate",
    courses_enrolled: 5,
    progress_percentage: 73,
    total_score: 1090,
    status: "active",
    createdAt: "2024-02-08",
    avatar: "/avatars/sebastian.jpg",
  },
  {
    id: "stud-26",
    name: "Scarlett Scott",
    email: "scarlett.scott@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-18",
    grade_level: "Advanced",
    courses_enrolled: 7,
    progress_percentage: 91,
    total_score: 1640,
    status: "active",
    createdAt: "2024-01-18",
    avatar: "/avatars/scarlett.jpg",
  },
  {
    id: "stud-27",
    name: "Jack Green",
    email: "jack.green@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-12",
    grade_level: "Beginner",
    courses_enrolled: 3,
    progress_percentage: 42,
    total_score: 380,
    status: "active",
    createdAt: "2024-03-12",
    avatar: "/avatars/jack.jpg",
  },
  {
    id: "stud-28",
    name: "Victoria Adams",
    email: "victoria.adams@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-22",
    grade_level: "Intermediate",
    courses_enrolled: 4,
    progress_percentage: 67,
    total_score: 890,
    status: "active",
    createdAt: "2024-02-22",
    avatar: "/avatars/victoria.jpg",
  },
  {
    id: "stud-29",
    name: "Henry Baker",
    email: "henry.baker@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-22",
    grade_level: "Advanced",
    courses_enrolled: 9,
    progress_percentage: 89,
    total_score: 1690,
    status: "active",
    createdAt: "2024-01-22",
    avatar: "/avatars/henry.jpg",
  },
  {
    id: "stud-30",
    name: "Grace Nelson",
    email: "grace.nelson@e-broker.com",
    role: "student",
    enrollment_date: "2024-04-05",
    grade_level: "Beginner",
    courses_enrolled: 1,
    progress_percentage: 18,
    total_score: 140,
    status: "active",
    createdAt: "2024-04-05",
    avatar: "/avatars/grace.jpg",
  },
  {
    id: "stud-31",
    name: "Samuel Carter",
    email: "samuel.carter@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-28",
    grade_level: "Intermediate",
    courses_enrolled: 6,
    progress_percentage: 76,
    total_score: 1150,
    status: "active",
    createdAt: "2024-02-28",
    avatar: "/avatars/samuel.jpg",
  },
  {
    id: "stud-32",
    name: "Chloe Mitchell",
    email: "chloe.mitchell@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-12",
    grade_level: "Advanced",
    courses_enrolled: 8,
    progress_percentage: 93,
    total_score: 1710,
    status: "active",
    createdAt: "2024-01-12",
    avatar: "/avatars/chloe.jpg",
  },
  {
    id: "stud-33",
    name: "Owen Perez",
    email: "owen.perez@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-18",
    grade_level: "Beginner",
    courses_enrolled: 2,
    progress_percentage: 30,
    total_score: 240,
    status: "inactive",
    createdAt: "2024-03-18",
    avatar: "/avatars/owen.jpg",
  },
  {
    id: "stud-34",
    name: "Lily Roberts",
    email: "lily.roberts@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-12",
    grade_level: "Intermediate",
    courses_enrolled: 5,
    progress_percentage: 71,
    total_score: 1020,
    status: "active",
    createdAt: "2024-02-12",
    avatar: "/avatars/lily.jpg",
  },
  {
    id: "stud-35",
    name: "Wyatt Turner",
    email: "wyatt.turner@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-28",
    grade_level: "Advanced",
    courses_enrolled: 7,
    progress_percentage: 84,
    total_score: 1480,
    status: "active",
    createdAt: "2024-01-28",
    avatar: "/avatars/wyatt.jpg",
  },
  {
    id: "stud-36",
    name: "Zoey Phillips",
    email: "zoey.phillips@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-22",
    grade_level: "Beginner",
    courses_enrolled: 3,
    progress_percentage: 36,
    total_score: 290,
    status: "active",
    createdAt: "2024-03-22",
    avatar: "/avatars/zoey.jpg",
  },
  {
    id: "stud-37",
    name: "Levi Campbell",
    email: "levi.campbell@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-16",
    grade_level: "Intermediate",
    courses_enrolled: 4,
    progress_percentage: 69,
    total_score: 950,
    status: "active",
    createdAt: "2024-02-16",
    avatar: "/avatars/levi.jpg",
  },
  {
    id: "stud-38",
    name: "Penelope Parker",
    email: "penelope.parker@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-08",
    grade_level: "Advanced",
    courses_enrolled: 9,
    progress_percentage: 96,
    total_score: 1780,
    status: "active",
    createdAt: "2024-01-08",
    avatar: "/avatars/penelope.jpg",
  },
  {
    id: "stud-39",
    name: "Grayson Evans",
    email: "grayson.evans@e-broker.com",
    role: "student",
    enrollment_date: "2024-04-08",
    grade_level: "Beginner",
    courses_enrolled: 1,
    progress_percentage: 12,
    total_score: 95,
    status: "active",
    createdAt: "2024-04-08",
    avatar: "/avatars/grayson.jpg",
  },
  {
    id: "stud-40",
    name: "Layla Edwards",
    email: "layla.edwards@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-02",
    grade_level: "Intermediate",
    courses_enrolled: 5,
    progress_percentage: 74,
    total_score: 1110,
    status: "active",
    createdAt: "2024-03-02",
    avatar: "/avatars/layla.jpg",
  },
  {
    id: "stud-41",
    name: "Nathan Collins",
    email: "nathan.collins@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-16",
    grade_level: "Advanced",
    courses_enrolled: 8,
    progress_percentage: 86,
    total_score: 1540,
    status: "active",
    createdAt: "2024-01-16",
    avatar: "/avatars/nathan.jpg",
  },
  {
    id: "stud-42",
    name: "Riley Stewart",
    email: "riley.stewart@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-26",
    grade_level: "Beginner",
    courses_enrolled: 2,
    progress_percentage: 27,
    total_score: 215,
    status: "active",
    createdAt: "2024-03-26",
    avatar: "/avatars/riley.jpg",
  },
  {
    id: "stud-43",
    name: "Elijah Sanchez",
    email: "elijah.sanchez@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-06",
    grade_level: "Intermediate",
    courses_enrolled: 6,
    progress_percentage: 77,
    total_score: 1190,
    status: "active",
    createdAt: "2024-02-06",
    avatar: "/avatars/elijah.jpg",
  },
  {
    id: "stud-44",
    name: "Nora Morris",
    email: "nora.morris@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-14",
    grade_level: "Advanced",
    courses_enrolled: 7,
    progress_percentage: 88,
    total_score: 1600,
    status: "active",
    createdAt: "2024-01-14",
    avatar: "/avatars/nora.jpg",
  },
  {
    id: "stud-45",
    name: "Carter Rogers",
    email: "carter.rogers@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-30",
    grade_level: "Beginner",
    courses_enrolled: 3,
    progress_percentage: 33,
    total_score: 270,
    status: "active",
    createdAt: "2024-03-30",
    avatar: "/avatars/carter.jpg",
  },
  {
    id: "stud-46",
    name: "Hannah Reed",
    email: "hannah.reed@e-broker.com",
    role: "student",
    enrollment_date: "2024-02-24",
    grade_level: "Intermediate",
    courses_enrolled: 4,
    progress_percentage: 66,
    total_score: 870,
    status: "active",
    createdAt: "2024-02-24",
    avatar: "/avatars/hannah.jpg",
  },
  {
    id: "stud-47",
    name: "Julian Cook",
    email: "julian.cook@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-26",
    grade_level: "Advanced",
    courses_enrolled: 9,
    progress_percentage: 92,
    total_score: 1730,
    status: "active",
    createdAt: "2024-01-26",
    avatar: "/avatars/julian.jpg",
  },
  {
    id: "stud-48",
    name: "Aria Morgan",
    email: "aria.morgan@e-broker.com",
    role: "student",
    enrollment_date: "2024-04-12",
    grade_level: "Beginner",
    courses_enrolled: 1,
    progress_percentage: 10,
    total_score: 80,
    status: "active",
    createdAt: "2024-04-12",
    avatar: "/avatars/aria.jpg",
  },
  {
    id: "stud-49",
    name: "Mateo Bell",
    email: "mateo.bell@e-broker.com",
    role: "student",
    enrollment_date: "2024-03-08",
    grade_level: "Intermediate",
    courses_enrolled: 5,
    progress_percentage: 70,
    total_score: 1000,
    status: "active",
    createdAt: "2024-03-08",
    avatar: "/avatars/mateo.jpg",
  },
  {
    id: "stud-50",
    name: "Hazel Murphy",
    email: "hazel.murphy@e-broker.com",
    role: "student",
    enrollment_date: "2024-01-04",
    grade_level: "Advanced",
    courses_enrolled: 10,
    progress_percentage: 97,
    total_score: 1850,
    status: "active",
    createdAt: "2024-01-04",
    avatar: "/avatars/hazel.jpg",
  },
];