import { AdminUser } from "../../types/user";

export const mockUsers: AdminUser[] = [
  {
    id: "admin-1",
    name: "Admin User",
    email: "admin@e-broker.com",
    role: "admin",
    permissions: ["all"],
    lastLogin: "2024-04-16",
    status: "active",
    createdAt: "2023-01-01",
    avatar: "/avatars/admin.jpg",
  },
  {
    id: "admin-2",
    name: "John Admin",
    email: "john.admin@e-broker.com",
    role: "admin",
    permissions: ["users.read", "users.write", "courses.read", "courses.write"],
    lastLogin: "2024-04-15",
    status: "active",
    createdAt: "2023-06-15",
    avatar: "/avatars/john-admin.jpg",
  },
  {
    id: "admin-3",
    name: "Sarah Manager",
    email: "sarah.manager@e-broker.com",
    role: "admin",
    permissions: ["users.read", "courses.read", "reports.read"],
    lastLogin: "2024-04-14",
    status: "active",
    createdAt: "2023-08-20",
    avatar: "/avatars/sarah-manager.jpg",
  },
  {
    id: "admin-4",
    name: "Mike Support",
    email: "mike.support@e-broker.com",
    role: "admin",
    permissions: ["users.read", "users.write"],
    lastLogin: "2024-04-10",
    status: "active",
    createdAt: "2024-01-10",
    avatar: "/avatars/mike-support.jpg",
  },
  {
    id: "admin-5",
    name: "Lisa Moderator",
    email: "lisa.moderator@e-broker.com",
    role: "admin",
    permissions: ["courses.read", "reports.read"],
    lastLogin: "2024-03-28",
    status: "inactive",
    createdAt: "2023-11-05",
    avatar: "/avatars/lisa-moderator.jpg",
  },
];
